import mongoose from 'mongoose';
import Ability from '../../../models/ability.js';
import Version from '../../../models/version.js';
import Config from '../../../config/config.js';

// Core/class druid abilities (with .jpg icons)
const coreAbilities = [
  {
    name: 'Barkskin',
    spell_id: '22812',
    description: 'Your skin becomes as tough as bark, reducing all damage you take by 20% for 12 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_stoneclawtotem.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 60,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Bear Form',
    spell_id: '5487',
    description: 'Transforms the druid into bear form, increasing armor by 370% and allowing the use of bear abilities.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_racial_bearform.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Cat Form',
    spell_id: '768',
    description: 'Transforms the druid into cat form, increasing movement speed by 30% and allowing the use of cat abilities.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_catform.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Cyclone',
    spell_id: '33786',
    description: 'Tosses the enemy into the air, preventing all action but making them invulnerable for up to 6 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_cyclone.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 20,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Dash',
    spell_id: '1850',
    description: 'Shift into Cat Form and increase your movement speed by 60% while in Cat Form for 10 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_dash.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 120,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Dreamwalk',
    spell_id: '193753',
    description: 'Opens a portal to the Emerald Dreamway.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_arcane_teleportstormwind.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Entangling Roots',
    spell_id: '339',
    description: 'Roots the target in place for up to 30 sec. Damage may cancel the effect.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_stranglevines.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 8,
    cooldown: 0,
    range: 35,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Ferocious Bite',
    spell_id: '22568',
    description: 'Finishing move that causes 1 Physical damage per combo point.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_ferociousbite.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 5,
    cost: 'Energy',
    cost_amount: 25
  },
  {
    name: 'Frenzied Regeneration',
    spell_id: '22842',
    description: 'Instantly heals you for 5% of your maximum health and for an additional 5% over 3 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_bullrush.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 72,
    range: 0,
    cost: 'Rage',
    cost_amount: 10
  },
  {
    name: 'Growl',
    spell_id: '6795',
    description: 'Taunts the target to attack you.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_physical_taunt.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 8,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Heart of the Wild',
    spell_id: '319454',
    description: 'Increases your Versatility by 6% and your maximum health by 15%.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_blessingofagility.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Hibernate',
    spell_id: '2637',
    description: 'Forces the enemy target to sleep for up to 40 sec. Any damage will awaken the target. Only one target can be forced to hibernate at a time.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_sleep.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Incapacitating Roar',
    spell_id: '99',
    description: 'Incapacitates all enemies within 10 yards for 3 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_demoralizingroar.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 10,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Innervate',
    spell_id: '29166',
    description: 'Increases the target\'s mana regeneration by 400% and allows 100% of their mana regeneration to continue while casting for 10 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_lightning.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 180,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Ironfur',
    spell_id: '192081',
    description: 'Increases your armor by 100% for 6 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_ironfur.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'Rage',
    cost_amount: 45
  },
  {
    name: 'Maim',
    spell_id: '22570',
    description: 'Finishing move that stuns the target for 1 sec per combo point.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_mangle-tga.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 5,
    cost: 'Energy',
    cost_amount: 35
  },
  {
    name: 'Mangle',
    spell_id: '33917',
    description: 'Mangle the target for 1 Physical damage and causes the target to take 30% additional damage from Bleed effects for 1 min.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_mangle2.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 10,
    cooldown: 6,
    range: 5,
    cost: 'Rage',
    cost_amount: 20
  },
  {
    name: 'Mark of the Wild',
    spell_id: '1126',
    description: 'Increases the target\'s armor by 5 and all attributes by 2 for 30 min.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_regeneration.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 10,
    cooldown: 0,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Mass Entanglement',
    spell_id: '102359',
    description: 'Roots all enemies within 15 yards in place for 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_massentanglement.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 60,
    range: 15,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Mighty Bash',
    spell_id: '5211',
    description: 'Stuns the target for 4 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_bash.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 50,
    range: 5,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Moonfire',
    spell_id: '8921',
    description: 'Burns the enemy for 1 Nature damage and then an additional 1 Nature damage over 12 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_starfall.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 4,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Moonkin Form',
    spell_id: '24858',
    description: 'Transforms the druid into Moonkin Form, increasing spell damage by 10% and allowing the use of balance abilities.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_forceofnature.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Mount Form',
    spell_id: '783',
    description: 'Transforms the druid into mount form, increasing movement speed by 40%.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_stagform.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Nature\'s Vigil',
    spell_id: '124974',
    description: 'Increases your damage and healing by 20% for 15 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/achievement_zone_feralas.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 90,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Prowl',
    spell_id: '5215',
    description: 'Allows the druid to sneak around, but reduces your movement speed by 30%.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_ambush.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Rake',
    spell_id: '1822',
    description: 'Rake the target for 1 Physical damage, and an additional 1 Physical damage over 9 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_disembowel.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 5,
    cost: 'Energy',
    cost_amount: 35
  },
  {
    name: 'Rebirth',
    spell_id: '20484',
    description: 'Returns the spirit to the body, restoring a dead target to life with 35% health.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_reincarnation.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 600,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Regrowth',
    spell_id: '8936',
    description: 'A fast heal that restores 1 health to an ally and has a 40% chance to apply Rejuvenation.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_resistnature.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 10,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Rejuvenation',
    spell_id: '774',
    description: 'Heals the target for 1 health over 12 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_rejuvenation.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 4,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Remove Corruption',
    spell_id: '2782',
    description: 'Removes 1 Curse and 1 Poison effect from a friendly target.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_removecurse.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 8,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Renewal',
    spell_id: '108238',
    description: 'Instantly heals you for 30% of your maximum health.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_natureblessing.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 90,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Revive',
    spell_id: '50769',
    description: 'Returns the spirit to the body, restoring a dead target to life with 35% health.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_reincarnation.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 600,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Rip',
    spell_id: '1079',
    description: 'Rip the target for 1 Physical damage over 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_ghoulfrenzy.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 5,
    cost: 'Energy',
    cost_amount: 30
  },
  {
    name: 'Shred',
    spell_id: '5221',
    description: 'Shred the target, causing 1 Physical damage to the target. Must be behind the target.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shadow_vampiricaura.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 10,
    cooldown: 0,
    range: 5,
    cost: 'Energy',
    cost_amount: 40
  },
  {
    name: 'Skull Bash',
    spell_id: '106839',
    description: 'Charges and interrupts the target, preventing any spell in that school from being cast for 4 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_bone_skull_04.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 15,
    range: 13,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Soothe',
    spell_id: '2908',
    description: 'Soothes an enraged beast, reducing its attack speed by 50% for 15 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_hunter_beastsoothe.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Stampeding Roar',
    spell_id: '106898',
    description: 'Increases the movement speed of all friendly players within 10 yards by 60% for 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_stampedingroar_cat.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 120,
    range: 10,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Starsurge',
    spell_id: '78674',
    description: 'Calls down a surge of stellar energy, causing 1 Arcane damage to the target and generating 20 Lunar Power.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_arcane_arcane03.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Sunfire',
    spell_id: '93402',
    description: 'Burns the enemy for 1 Nature damage and then an additional 1 Nature damage over 12 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_mage_firestarter.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Swipe',
    spell_id: '106785',
    description: 'Swipe all enemies within 8 yards for 1 Physical damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_monsterclaw_03.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 8,
    cost: 'Rage',
    cost_amount: 35
  },
  {
    name: 'Symbiotic Relationship',
    spell_id: '207400',
    description: 'Creates a symbiotic link with a friendly target, sharing damage and healing between you.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_focusedgrowth.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 120,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Thrash',
    spell_id: '106830',
    description: 'Thrash all enemies within 8 yards for 1 Physical damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_thrash.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 8,
    cost: 'Rage',
    cost_amount: 35
  },
  {
    name: 'Tiger Dash',
    spell_id: '252216',
    description: 'Increases your movement speed by 200% for 5 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_dash_orange.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 45,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Travel Form',
    spell_id: '783',
    description: 'Transforms the druid into travel form, increasing movement speed by 40%.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_travelform.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Treant Form',
    spell_id: '114282',
    description: 'Transforms the druid into Treant Form, increasing healing done by 25% and allowing the use of restoration abilities.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_treeoflife.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Typhoon',
    spell_id: '132469',
    description: 'Blasts enemies within 15 yards away from you, dealing 1 Nature damage and knocking them back.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_typhoon.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 30,
    range: 15,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Ursol\'s Vortex',
    spell_id: '102793',
    description: 'Creates a vortex at the target location, pulling enemies toward the center and reducing their movement speed by 50%.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_ursolsvortex.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 60,
    range: 30,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Wild Charge',
    spell_id: '102401',
    description: 'Grants a movement ability that varies by shapeshift form.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_wildcharge.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 15,
    range: 25,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Convoke the Spirits',
    spell_id: '391528',
    description: 'Call upon the spirits for an eruption of energy, channeling a rapid flurry of 16 Druid spells and abilities over 4 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_ability_druid_convokethespirits.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 120,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Wild Growth',
    spell_id: '48438',
    description: 'Heals up to 5 injured party or raid members for 1 health over 7 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_flourish.jpg',
    class: 'druid',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 10,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },

];

// Spec/hero talent actives and replacements
const specAndHeroActives = [
  // Balance spec actives
  {
    name: 'Celestial Alignment',
    spell_id: '194223',
    description: 'Aligns the stars, increasing your damage and healing by 20% for 15 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_natureguardian.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 180,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },

  {
    name: 'Fury of Elune',
    spell_id: '202770',
    description: 'Calls down a beam of pure starlight, dealing 1 Arcane damage to all enemies within 8 yards every 0.5 sec for 4 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_dreamstate.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 60,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Incarnation: Chosen of Elune',
    spell_id: '102560',
    description: 'Transforms the druid into the Chosen of Elune, increasing damage by 25% and allowing the use of balance abilities.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_incarnation.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 180,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },

  {
    name: 'New Moon',
    spell_id: '274281',
    description: 'Throws a New Moon at the target, dealing 1 Arcane damage and generating 10 Lunar Power.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/artifactability_balancedruid_newmoon.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Solar Beam',
    spell_id: '78675',
    description: 'Calls down a beam of solar light, dealing 1 Nature damage to the target and silencing them for 3 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_vehicle_electrocharge.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 60,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Starfall',
    spell_id: '191034',
    description: 'Calls down waves of falling stars upon enemies within 40 yards for 8 sec, dealing 1 Arcane damage every 1 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_starfall.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 120,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Stellar Flare',
    spell_id: '202347',
    description: 'Burns the target for 1 Arcane damage and then an additional 1 Arcane damage over 24 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_stellarflare.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Warrior of Elune',
    spell_id: '202425',
    description: 'Increases your damage by 20% and reduces the cost of your abilities by 20% for 15 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_elunesgrace.jpg',
    class: 'druid',
    spec: 'balance',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 90,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  // Feral spec actives
  {
    name: 'Adaptive Swarm',
    spell_id: '391888',
    description: 'Commands a swarm of insects to attack the target, dealing 1 Nature damage over 12 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_ability_druid_adaptiveswarm.jpg',
    class: 'druid',
    spec: 'feral',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 25,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Brutal Slash',
    spell_id: '202028',
    description: 'Slash all enemies within 8 yards for 1 Physical damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_ravage.jpg',
    class: 'druid',
    spec: 'feral',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 8,
    cost: 'Energy',
    cost_amount: 45
  },

  {
    name: 'Feral Frenzy',
    spell_id: '274837',
    description: 'Unleash a furious assault, causing 1 Physical damage to the target over 4 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_rake.jpg',
    class: 'druid',
    spec: 'feral',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 45,
    range: 5,
    cost: 'Energy',
    cost_amount: 25
  },
  {
    name: 'Incarnation: Avatar of Ashamane',
    spell_id: '102543',
    description: 'Transforms the druid into the Avatar of Ashamane, increasing damage by 25% and allowing the use of feral abilities.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_incarnation.jpg',
    class: 'druid',
    spec: 'feral',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 180,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  // Guardian spec actives
  {
    name: 'Berserk',
    spell_id: '106951',
    description: 'Increases your damage by 50% and reduces the cost of your abilities by 50% for 15 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_berserk.jpg',
    class: 'druid',
    spec: 'guardian',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 180,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Bristling Fur',
    spell_id: '155835',
    description: 'Increases your armor by 200% for 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_bristlingfur.jpg',
    class: 'druid',
    spec: 'guardian',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 45,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Challenging Roar',
    spell_id: '5209',
    description: 'Challenges all enemies within 10 yards to attack you for 6 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_challangingroar.jpg',
    class: 'druid',
    spec: 'guardian',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 300,
    range: 10,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Demoralizing Roar',
    spell_id: '99',
    description: 'Reduces the attack power of all enemies within 10 yards by 5 for 30 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_demoralizingroar.jpg',
    class: 'druid',
    spec: 'guardian',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 10,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Maul',
    spell_id: '6807',
    description: 'Maul the target for 1 Physical damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_maul.jpg',
    class: 'druid',
    spec: 'guardian',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 5,
    cost: 'Rage',
    cost_amount: 45
  },
  {
    name: 'Survival Instincts',
    spell_id: '61336',
    description: 'Reduces all damage you take by 50% for 6 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_tigersroar.jpg',
    class: 'druid',
    spec: 'guardian',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 180,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  // Restoration spec actives
  {
    name: 'Cenarion Ward',
    spell_id: '102351',
    description: 'Protects a friendly target. When the target takes damage, they are instantly healed for 1 health.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_naturalperfection.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 30,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },

  {
    name: 'Efflorescence',
    spell_id: '145205',
    description: 'Creates a healing grove at the target location, healing all allies within 10 yards for 1 health every 2 sec for 30 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_talandrasrose.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Flourish',
    spell_id: '197721',
    description: 'Extends the duration of all your heal over time effects on friendly targets within 60 yards by 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_wildburst.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 90,
    range: 60,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Grove Guardian',
    spell_id: '383191',
    description: 'Summons a Grove Guardian that heals nearby allies for 1 health every 2 sec for 15 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_forceofnature.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 60,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Incarnation: Tree of Life',
    spell_id: '33891',
    description: 'Transforms the druid into the Tree of Life, increasing healing done by 25% and allowing the use of restoration abilities.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_treeoflife.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 180,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Invigorate',
    spell_id: '392160',
    description: 'Instantly heals the target for 1 health and increases their maximum health by 10% for 10 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_preservation.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 30,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Ironbark',
    spell_id: '102342',
    description: 'Reduces all damage the target takes by 20% for 12 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_druid_ironbark.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 90,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Lifebloom',
    spell_id: '33763',
    description: 'Heals the target for 1 health over 15 sec. When Lifebloom expires, it instantly heals the target for 1 health.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_misc_herb_felblossom.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Nature\'s Swiftness',
    spell_id: '132158',
    description: 'Your next Nature spell with a cast time less than 10 sec becomes an instant cast spell.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_ravenform.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 60,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Nourish',
    spell_id: '50464',
    description: 'Heals a friendly target for 1 health. Healing is increased by 20% if you have a Rejuvenation, Regrowth, Lifebloom, or Wild Growth effect active on the target.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_nourish.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Overgrowth',
    spell_id: '203651',
    description: 'Applies Lifebloom, Rejuvenation, Regrowth, and Wild Growth to the target.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_overgrowth.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 60,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Nature\'s Cure',
    spell_id: '88423',
    description: 'Removes all harmful magical effects, curses, and poison effects from a friendly target.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_cleansespirit.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 8,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Revitalize',
    spell_id: '388614',
    description: 'Instantly heals the target for 1 health and increases their maximum health by 10% for 10 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_druid_empoweredtouch.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 30,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Swiftmend',
    spell_id: '18562',
    description: 'Consumes a Rejuvenation or Regrowth effect to instantly heal the target for 1 health.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_relics_idolofrejuvenation.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 15,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Tranquility',
    spell_id: '740',
    description: 'Heals all party and raid members within 40 yards for 1 health every 2 sec for 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_tranquility.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 0,
    cooldown: 480,
    range: 40,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Wrath',
    spell_id: '5176',
    description: 'Causes 1 Nature damage to the target.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_wrathv2.jpg',
    class: 'druid',
    spec: 'restoration',
    hero_talent: null,
    ability_type: 'spec',
    level_required: 1,
    cooldown: 0,
    range: 40,
    cost: 'None',
    cost_amount: 0
  }
];

async function seedDruidAbilities() {
  try {
    console.log('Connecting to database...');
    await mongoose.connect(Config.databaseURI);
    console.log('Connected.');

    const versions = await Version.find();
    if (!versions.length) {
      console.error('No versions found!');
      return;
    }

    // Delete all druid abilities for all versions
    const del = await Ability.deleteMany({ class: 'druid' });
    console.log(`Deleted ${del.deletedCount} druid abilities.`);

    let created = 0;
    for (const version of versions) {
      // For each spec (including null for class abilities)
      const specs = [null, 'balance', 'feral', 'guardian', 'restoration'];
      for (const spec of specs) {
        // --- Seed core/class abilities, skipping those replaced by hero/spec talents for this spec ---
        for (const ability of coreAbilities) {
          // Check for spec-level replacements
          const specReplaced = spec && specAndHeroActives.find(a =>
            a.replaces === ability.name &&
            a.spec === spec &&
            a.hero_talent === null
          );

          // Check for hero talent replacements (for all hero talents of this spec)
          const heroTalentReplaced = spec && specAndHeroActives.find(a =>
            a.replaces === ability.name &&
            a.spec === spec &&
            a.hero_talent !== null
          );

          if (specReplaced || heroTalentReplaced) continue;
          await Ability.create({ ...ability, spec, game_version: version._id });
          created++;
        }
      }
      // --- Seed spec/hero actives, handling replacements ---
      for (const ability of specAndHeroActives) {
        await Ability.create({ ...ability, game_version: version._id });
        created++;
      }
    }
    console.log(`Seeded ${created} druid abilities for ${versions.length} versions.`);
  } catch (e) {
    console.error('Error:', e);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected.');
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  seedDruidAbilities();
}

export default seedDruidAbilities;
