const coreAbilities = [
  {
    name: 'Ancestral Spirit',
    spell_id: '2008',
    description: 'Returns the spirit to the body, restoring a dead target to life with 35% health and mana.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_regenerate.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Astral Recall',
    spell_id: '556',
    description: 'Returns you to your Hearthstone location.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_astralrecal.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 30,
    cooldown: 900,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Astral Shift',
    spell_id: '108271',
    description: 'Shifts partially into the elemental planes, taking 40% less damage for 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_astralshift.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 90,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Bloodlust',
    spell_id: '2825',
    description: 'Increases haste by 30% for all party and raid members for 40 sec. (Horde only)',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_bloodlust.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 60,
    cooldown: 300,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Heroism',
    spell_id: '32182',
    description: 'Increases haste by 30% for 40 sec (Alliance only).',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_holy_heroism.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 60,
    cooldown: 300,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Chain Heal',
    spell_id: '1064',
    description: 'Heals the friendly target for a moderate amount, then jumps to heal additional nearby friendly targets.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_healingwavegreater.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Chain Lightning',
    spell_id: '188443',
    description: 'Hurls a lightning bolt at the enemy, dealing Nature damage and then jumping to additional nearby enemies.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_chainlightning.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Cleanse Spirit',
    spell_id: '51886',
    description: 'Removes all Curse and Magic effects from a friendly target.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_cleansespirit.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Earth Elemental',
    spell_id: '198103',
    description: 'Calls forth a Greater Earth Elemental to protect you and your allies for 1 min.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_earthelemental_totem.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 300,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Earthbind Totem',
    spell_id: '2484',
    description: 'Summons a totem at your feet for 20 sec that slows the movement speed of enemies within 10 yards by 50%.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_strengthofearthtotem02.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Far Sight',
    spell_id: '6196',
    description: 'Changes your viewpoint to the targeted location for 1 min.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_farsight.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Flame Shock',
    spell_id: '188389',
    description: 'Sears the target with fire, causing Fire damage and then additional Fire damage over 18 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_flameshock.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Frost Shock',
    spell_id: '196840',
    description: 'Instantly shocks the target with ice, dealing Frost damage and reducing movement speed by 50% for 6 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_frost_frostshock.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Ghost Wolf',
    spell_id: '2645',
    description: 'Transforms you into a ghost wolf, increasing movement speed by 30%.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_spiritwolf.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Healing Surge',
    spell_id: '8004',
    description: 'A quick but inefficient surge of healing energy that restores health to an ally.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_healingway.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Healing Stream Totem',
    spell_id: '5394',
    description: 'Summons a totem at your feet for 15 sec that heals an injured party or raid member within 40 yards every 2 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_spear_04.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Hex',
    spell_id: '51514',
    description: 'Transforms the enemy into a frog for 8 sec. The hexed target cannot attack or cast spells.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_hex.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Lightning Bolt',
    spell_id: '188196',
    description: 'Hurls a bolt of lightning at the target, dealing Nature damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_lightning.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Lava Burst',
    spell_id: '51505',
    description: 'Hurls molten lava at the target, dealing Fire damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_lavaburst.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Lightning Shield',
    spell_id: '192106',
    description: 'Surrounds you with lightning, dealing Nature damage to attackers.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_lightningshield.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: "Nature's Swiftness",
    spell_id: '378081',
    description: 'Your next Nature spell with a base cast time less than 10 sec becomes an instant cast spell.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_ravenform.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Purge',
    spell_id: '370',
    description: 'Purges the enemy target, removing 1 beneficial magic effect.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_purge.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Reincarnation',
    spell_id: '20608',
    description: 'Allows you to resurrect yourself with 20% health and mana when you die.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_improvedreincarnation.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 1800,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: "Spiritwalker's Grace",
    spell_id: '79206',
    description: 'Calls upon spiritual guidance, allowing movement while casting Shaman spells.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_spiritwalkersgrace.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Spirit Walk',
    spell_id: '58875',
    description: 'Removes all movement impairing effects and increases your movement speed by 60% for 8 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_tracking.jpg',
    class: 'shaman',
    spec: 'Enhancement',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Totemic Projection',
    spell_id: '108287',
    description: 'Relocates your active totems to the specified location.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_totemrelocation.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Water Walking',
    spell_id: '546',
    description: 'Allows you to walk on water for 10 min.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_frost_windwalkon.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Wind Rush Totem',
    spell_id: '192077',
    description: 'Summons a totem at your feet for 15 sec that grants 60% increased movement speed to you and allies within 10 yards.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_windwalktotem.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Capacitor Totem',
    spell_id: '192058',
    description: 'Summons a totem at your feet for 3 sec that stuns enemies within 8 yards for 3 sec when it expires.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_brilliance.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Earthgrab Totem',
    spell_id: '51485',
    description: 'Summons a totem at your feet for 20 sec that roots enemies within 8 yards for 5 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_natureswrath.jpg',
    class: 'shaman',
    spec: null,
    hero_talent: null,
    ability_type: 'class',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Maelstrom Weapon',
    spell_id: '51530',
    description: 'When you deal damage with a melee weapon, you have a chance to gain Maelstrom Weapon, reducing the cast time and mana cost of your next spell.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_unrelentingstorm.jpg',
    class: 'shaman',
    spec: 'Enhancement',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Feral Spirit',
    spell_id: '51533',
    description: 'Summons two Spirit Wolves to fight for you for 15 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_feralspirit.jpg',
    class: 'shaman',
    spec: 'Enhancement',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Windfury Weapon',
    spell_id: '33757',
    description: 'Imbue your weapon with the element of wind for 1 hour, giving each attack a chance to strike an additional time.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_cyclone.jpg',
    class: 'shaman',
    spec: 'Enhancement',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Flametongue Weapon',
    spell_id: '318038',
    description: 'Imbue your weapon with the element of fire for 1 hour, causing each attack to deal additional Fire damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_flametounge.jpg',
    class: 'shaman',
    spec: 'Enhancement',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Spirit Link Totem',
    spell_id: '98008',
    description: 'Summons a totem that links the health of all nearby party and raid members, equalizing the percentage of health among them every second.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_spiritlink.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Healing Tide Totem',
    spell_id: '108280',
    description: 'Summons a totem that heals all party and raid members within 40 yards every 2 sec for 10 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_healingtide.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Earth Shield',
    spell_id: '974',
    description: 'Protects the target with an earthen shield, increasing healing received and healing them when they take damage. Only one Earth Shield can be active on a target at a time.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_skinofearth.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Lava Lash',
    spell_id: '60103',
    description: 'Imbue your off-hand weapon with lava, instantly dealing Fire damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_lavalash.jpg',
    class: 'shaman',
    spec: 'Enhancement',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Riptide',
    spell_id: '61295',
    description: 'Heals a friendly target instantly and over time.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_riptide.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Healing Rain',
    spell_id: '73920',
    description: 'Calls down healing rain, healing all allies in the area over 10 sec.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_healingway.jpg',
    class: 'shaman',
    spec: 'Restoration',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Elemental Blast',
    spell_id: '117014',
    description: 'Blasts the enemy with a surge of elemental power, dealing Elemental damage and increasing a secondary stat.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_elementalblast.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  },
  {
    name: 'Stormstrike',
    spell_id: '17364',
    description: 'Strikes the target with both weapons, dealing Physical and Nature damage.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_lightning.jpg',
    class: 'shaman',
    spec: 'Enhancement',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 0,
    cost: 'None',
    cost_amount: 0
  },
  {
    name: 'Earthquake',
    spell_id: '61882',
    description: 'Causes the earth within 8 yards of the target location to tremble and break, dealing Physical damage over 6 sec and sometimes knocking down enemies.',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_earthquake.jpg',
    class: 'shaman',
    spec: 'Elemental',
    hero_talent: null,
    ability_type: 'spell',
    level_required: 0,
    cooldown: 0,
    range: 40,
    cost: 'Mana',
    cost_amount: 0
  }
];

// --- Spec and Talent Abilities ---
const specAbilities = {
  elemental: {
    abilities: [
      {
        id: 1,
        spell_id: '212056',
        name: 'Absolution',
        description: 'Returns all dead party members to life with 35% of maximum health and mana. Cannot be cast when in combat.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_sword_48.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 2,
        spell_id: '188389',
        name: 'Flame Shock',
        description: 'Ignites the target, causing fire damage over time.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_flameshock.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 3,
        spell_id: '196840',
        name: 'Frost Shock',
        description: 'Deals frost damage and slows the target.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_frost_frostshock.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 4,
        spell_id: '8042',
        name: 'Earth Shock',
        description: 'Instantly shocks the target, dealing nature damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_earthshock.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 5,
        spell_id: '51505',
        name: 'Lava Burst',
        description: 'Hurls molten lava at the target. Always critically strikes if Flame Shock is active.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_lavaburst.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 6,
        spell_id: '188196',
        name: 'Lightning Bolt',
        description: 'Hurls a bolt of lightning at the target, dealing nature damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_lightning.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 7,
        spell_id: '188443',
        name: 'Chain Lightning',
        description: 'Strikes the primary target with a bolt of lightning that arcs to additional enemies.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_chainlightning.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 8,
        spell_id: '117014',
        name: 'Elemental Blast',
        description: 'Unleashes a blast of elemental fury at the target, dealing damage and granting a chance to hit bonus.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_elementalblast.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 9,
        spell_id: '191634',
        name: 'Stormkeeper',
        description: 'Calls upon the power of storms, empowering your next Lightning Bolt or Chain Lightning.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_stormkeeper.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 10,
        spell_id: '16166',
        name: 'Elemental Mastery',
        description: 'Increases your critical strike chance and guarantees your next spell is a critical strike.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_wispsleep.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 11,
        spell_id: '114049',
        name: 'Ascendance',
        description: 'Transform into an Ascended Elemental, gaining powerful new spells for a short duration.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_ascendance.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ],
    farseer: [
      {
        id: 12,
        spell_id: '61882',
        name: 'Earthquake',
        description: 'Creates an earthquake that damages all enemies in the area over time.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_earthquake.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 13,
        spell_id: '382461',
        name: 'Conduction',
        description: 'Your elemental spells generate additional Maelstrom for each critical strike.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_focusedconduit.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 14,
        spell_id: '198838',
        name: 'Earthen Shield Totem',
        description: 'Summons an Earthen Shield Totem that grants an absorb shield to nearby allies.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_earthenshieldtotem.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 15,
        spell_id: '382457',
        name: 'Elemental Fusion',
        description: 'Your elemental damage spells empower each other, increasing their effectiveness.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_primallongevity.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ],
    stormbringer: [
      {
        id: 16,
        spell_id: '382451',
        name: 'Coalescing Storm',
        description: 'Absorbs incoming damage and releases it as a powerful storm blast.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_stormsurge.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 17,
        spell_id: '383076',
        name: 'Primal Elementalist',
        description: 'Summons primal elemental minions to fight alongside you.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_primalelementalist.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 18,
        spell_id: '382470',
        name: 'Fury of Air',
        description: 'Increases your Haste and Critical Strike for a short time.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_furyofair.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 19,
        spell_id: '382474',
        name: 'Tempest Mastery',
        description: 'Your Lightning Bolt and Chain Lightning deal increased damage and jump further.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_tempestmastery.jpg',
        class: 'shaman',
        spec: 'Elemental',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 10,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ]
  },
  enhancement: {
    abilities: [
      {
        id: 20,
        spell_id: '17364',
        name: 'Stormstrike',
        description: 'Strikes the target with lightning, dealing Physical and Nature damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_lightning.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 21,
        spell_id: '60103',
        name: 'Lava Lash',
        description: 'Imbue your weapon with lava, causing your next melee attack to deal Fire damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_lavalash.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 22,
        spell_id: '193786',
        name: 'Rockbiter Attack',
        description: 'Empowers your weapon with earth, dealing increased Physical damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_stonebite.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 23,
        spell_id: '196834',
        name: 'Frostbrand Attack',
        description: 'Imbue your weapon with frost, slowing the target.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_frostbrand.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 24,
        spell_id: '188389',
        name: 'Flame Shock',
        description: 'Ignites the target, causing Fire damage over time.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_flameshock.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 25,
        spell_id: '196840',
        name: 'Frost Shock',
        description: 'Deals Frost damage and slows the target.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_frost_frostshock.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 26,
        spell_id: '73680',
        name: 'Unleash Elements',
        description: 'Empowers your next damaging or healing spell based on your specialization.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_unleashweapon.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ],
    stormbringer: [
      {
        id: 27,
        spell_id: '373188',
        name: 'Landfall',
        description: 'A barrage of attacks that deal increased damage to your primary target.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_landfall.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 28,
        spell_id: '373195',
        name: 'Crushing Storm',
        description: 'Empowers your auto-attacks to deal Nature damage in an area.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_crushingstorm.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 29,
        spell_id: '374251',
        name: 'Seismic Bore',
        description: 'Unleashes a shockwave that damages and knocks down enemies.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_seismicwell.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ],
    totemic: [
      {
        id: 30,
        spell_id: '3599',
        name: 'Searing Totem',
        description: 'Summons a totem that burns enemies, dealing Fire damage over time.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_searingtotem.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 31,
        spell_id: '8190',
        name: 'Magma Totem',
        description: 'Creates a totem that erupts periodically, dealing Fire damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_fire_impoweringtotem.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 32,
        spell_id: '383947',
        name: 'Poison Cloud Totem',
        description: 'Summons a totem that emits poisonous clouds, damaging enemies over time.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_poisoncloud.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 33,
        spell_id: '381652',
        name: 'Seal of the Searsplinter',
        description: 'Surrounds you with elemental energy, reducing damage taken and shocking attackers.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_elementaloasis.jpg',
        class: 'shaman',
        spec: 'Enhancement',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ]
  },
  restoration: {
    abilities: [
      {
        id: 34,
        spell_id: '77472',
        name: 'Healing Wave',
        description: 'Heals a friendly target for a large amount.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_healingwavegreater.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 35,
        spell_id: '1064',
        name: 'Chain Heal',
        description: 'Heals a target and then jumps to additional injured allies.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_chainheal.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 36,
        spell_id: '61295',
        name: 'Riptide',
        description: 'Heals the target and applies a HoT effect.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_riptide.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 37,
        spell_id: '73920',
        name: 'Healing Rain',
        description: 'Summons a rain of healing drops at the target location.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_healingway.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 38,
        spell_id: '974',
        name: 'Earth Shield',
        description: 'Shields the target and heals them when they take damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_skinofearth.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 40,
        cost: 'Mana',
        cost_amount: 0
      },
      {
        id: 39,
        spell_id: '191861',
        name: 'Spirit of the Maelstrom',
        description: 'Increases your casting speed after dealing Nature, Frost, or Storm damage.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_spiritlink.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 40,
        spell_id: '73680',
        name: 'Unleash Elements',
        description: 'Empowers your next damaging or healing spell based on your specialization.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_unleashweapon.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ],
    farseer: [
      {
        id: 41,
        spell_id: '2484',
        name: 'Earthbind Totem',
        description: 'Summons a totem that slows enemy movement speed.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_nature_stranglevines.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 42,
        spell_id: '198839',
        name: 'Earthen Wall Totem',
        description: 'Places a wall that blocks enemy movement.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_earthenwalltotem.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ],
    totemic: [
      {
        id: 43,
        spell_id: '383932',
        name: 'Totemic Projection',
        description: 'Places your totems at a greater distance from you.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_totemicprojection.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 44,
        spell_id: '210643',
        name: 'Totemic Mastery',
        description: 'Reduces the mana cost of your totems by 50%.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/spell_shaman_totemrelocation.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      },
      {
        id: 45,
        spell_id: '377719',
        name: 'Echo of the Elements',
        description: 'Your healing totems cast their healing spell an additional time.',
        icon: 'https://wow.zamimg.com/images/wow/icons/large/ability_shaman_echooftheelements.jpg',
        class: 'shaman',
        spec: 'Restoration',
        hero_talent: null,
        ability_type: 'spell',
        level_required: 0,
        cooldown: 0,
        range: 0,
        cost: 'None',
        cost_amount: 0
      }
    ]
  }
};

// --- Export ---
export default { coreAbilities, specAbilities };
// To use: import { coreAbilities, specAbilities } from './shaman_merged.js';
// All spell_id fields are strings for consistency with seedShamanAbilities.js format.
